name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: mkdocs-${{ hashFiles('**/*requirements.txt') }}-${{ hashFiles('mkdocs.yml') }}
          path: |
            ~/.cache/pip
            **/__pycache__
          restore-keys: |
            mkdocs-
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force